#%RAML 1.0
title: NMOS Control Event API
version: v0.1
baseUri: http://myapi.mysite.com/api/{version}
mediaType: application/json
schemas:
  - ControlEventGrain: !include schemas/ControlEventGrain.json
	EmptySchema: !include schemas/Emptyjson
	ErrorSchema: !include schemas/Error.json

/:
  displayName: Interface for controlling part of a Flow
  post:
	body:
		application/json:
			example: !include ../examples/CrosspointSwitch.json
			schema: ControlEventGrain
    responses:
		200:
			schema: EmptySchema
		400:
			schema: ErrorSchema